
HTTP_STATUS_NOT_MODIFIED = 304
HTTP_STATUS_BAD_REQUEST  = 400
HTTP_STATUS_UNAUTHORIZED  = 401
HTTP_STATUS_FORBIDDEN = 403
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_GONE = 410
HTTP_STATUS_ENHANCE_YOUR_CALM = 420
HTTP_STATUS_UNPROCESSABLE_ENTITY = 422
HTTP_STATUS_TOO_MANY_REQUESTS = 429
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
HTTP_STATUS_BAD_GATEWAY = 502
HTTP_STATUS_SERVICE_UNAVAILABLE = 503
HTTP_STATUS_GATEWAY_TIMEOUT = 504
